id: loop_short_announcement
type: info
dismissable: true
msg: |
  <strong>New: OnDemand Loop (Beta)</strong> – Streamline data transfers between your HPC environment and repositories like Dataverse and Zenodo.  
  Access it under <strong><a href="/pun/sys/loop">Files &gt; OnDemand Loop</a></strong> (restart OOD via <em>Help &gt; Restart Web Server</em> if it doesn’t appear).