navigation:
  - id: help
    items:
      - id: 'fasrc-support-url'
        label: 'Contact Support'
        icon: 'bs://bi-life-preserver'
        url: 'https://www.rc.fas.harvard.edu/about/contact/'
        position: 1
        new_tab: true
      - id: 'fasrc-password-url'
        label: 'Change HPC Password'
        icon: 'bs://bi-key'
        url: 'https://portal.rc.fas.harvard.edu/pwreset/'
        position: 1
        new_tab: true
      - label: '---'
        position: 1