name: Build from Tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print build parameters
        run: |
          echo "🔧 Build with parameters:"
          echo "  - tag: ${{ inputs.tag }}"
          echo "  - environment: ${{ inputs.environment }}"
          echo "  - branch: ${{ inputs.branch }}"

      - name: Checkout Loop Tags
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0

      - name: Git setup
        working-directory: src
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Checkout source repo at tag
        uses: actions/checkout@v4
        with:
          repository: IQSS/ondemand-loop
          ref: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src

      - name: Build artifacts
        working-directory: src
        run: make release_build

      - name: Checkout target
        uses: actions/checkout@v4
        with:
          path: target

      - name: Checkout or create target branch
        working-directory: target
        run: |
          source .github/scripts/utils.sh

          if git ls-remote --exit-code --heads origin "${{ inputs.branch }}"; then
            set_output "message" "✅ **Branch '${{ inputs.branch }}' exists. Checking it out**"
            git checkout "${{ inputs.branch }}"
          else
            set_output "message" "🆕 **Branch '${{ inputs.branch }}' does not exist. Creating it from origin/main**"
            git checkout -b "${{ inputs.branch }}" origin/main
          fi

      - name: Copy build code
        run: |
          rsync -a --delete --exclude='.git' src/application/ target/

      - name: List contents of target
        run: ls -la target/

      - name: Commit build
        working-directory: target
        run: |
          git add .
          git commit -m "OnDemand Loop deployment for version ${{ inputs.tag }}"
          git push
