name: Build from Tag/Commit

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print build parameters
        run: |
          echo "🔧 Build with parameters:"
          echo "  - commit_hash: ${{ inputs.commit_hash }}"
          echo "  - tag: ${{ inputs.tag }}"
          echo "  - environment: ${{ inputs.environment }}"
          echo "  - branch: ${{ inputs.branch }}"

      - name: Checkout Loop Tags
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0

      - name: Git setup
        working-directory: src
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Checkout source repo at tag
        uses: actions/checkout@v4
        with:
          repository: IQSS/ondemand-loop
          ref: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src

      - name: Build artifacts
        working-directory: src
        run: make release_build

      - name: Checkout target
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          path: target

      - name: Prepare target branch
        working-directory: target
        run: |
          git checkout -B "${{ inputs.branch }}"

      - name: Copy build code
        run: |
          rsync -a --delete --exclude='.git' src/application/ target/

      - name: Checkout FASRC config
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash }}
          path: fasrc_config

      - name: Copy FASRC configuration
        run: |
          cp -R fasrc_config/config/fasrc/. target

      - name: List contents of target
        run: ls -la target/

      - name: Commit build
        working-directory: target
        run: |
          git add .
          git commit -m "OnDemand Loop deployment build for OnDemand Loop ${{ inputs.tag }}"
          git push origin "${{ inputs.branch }}" --force
