name: FASRC Deployment Build

on:
  repository_dispatch:
    types: [deployment_build_command]

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract.outputs.tag }}
      env: ${{ steps.extract.outputs.env }}
      branch: ${{ steps.extract.outputs.branch }}
      message: ${{ steps.extract.outputs.message || steps.approval.outputs.message }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version and map environment to branch
        id: extract
        run: |
          source .github/scripts/utils.sh

          ENVIRONMENT="${{ github.event.client_payload.slash_command.args.named.env }}"
          ENVIRONMENT=$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')
          ISSUE_NUMBER="${{ github.event.client_payload.github.payload.issue.number }}"
          TITLE=$(gh issue view "$ISSUE_NUMBER" --repo "${{ github.repository }}" --json title --jq '.title')
          TAG=$(echo "$TITLE" | grep -oE 'version: *[^ ]+' | sed 's/version: *//')
          
          if [[ ! "$TITLE" =~ ^[Dd]eployment [Bb]uild ]]; then
            set_output "message" "❌ **Issue title must start with Deployment Build**"
            exit 1
          fi

          case "$ENVIRONMENT" in
            qa)
              BRANCH="iqss_qa"
              ;;
            production)
              BRANCH="iqss_production_${TAG//+/-}"
              ;;
            *)
              set_output "message" "❌ **Unknown environment: $ENVIRONMENT**"
              exit 1
              ;;
          esac

          set_output "env" "$ENVIRONMENT"
          set_output "tag" "$TAG"
          set_output "branch" "$BRANCH"
          
          # Final validation
          if [[ -z "$ENVIRONMENT" || -z "$TAG" || -z "$BRANCH" ]]; then
            set_output "message" "❌ **Environment, tag, and branch are required values**"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Require approval for Production
        id: approval
        if: ${{ steps.extract.outputs.env == 'production' }}
        run: |
          source .github/scripts/utils.sh
          
          ISSUE="${{ github.event.client_payload.github.payload.issue.number }}"
          APPROVED=$(gh issue view "$ISSUE" --repo "${{ github.repository }}" --json comments --jq \
            '.comments[].body | select(test("(?i)build approved"))')

          if [ -z "$APPROVED" ]; then
            set_output "message" "❌ **Build not approved. Aborting.**"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: validate
    uses: ./.github/workflows/build_from_tag.yml
    with:
      tag: ${{ needs.validate.outputs.tag }}
      environment: ${{ needs.validate.outputs.env }}
      branch: ${{ needs.validate.outputs.branch }}

  comment:
    name: Comment on completion
    needs: [ validate, build ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compose result title
        id: title
        run: |
          source .github/scripts/utils.sh
          
          STATUS="${{ needs.build.result }}"
          if [ "$STATUS" = "success" ]; then
            set_output "title" "✅ **Deployment build succeeded**"
          else
            set_output "title" "❌ **Deployment build failed**"
          fi

      - name: Post completion comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            ${{ steps.title.outputs.title }}
            
            ${{ needs.validate.outputs.message }}
      
            **Version**: `${{ needs.validate.outputs.tag || 'N/A' }}`  
            **Environment**: `${{ needs.validate.outputs.env || 'N/A' }}`
            **Branch**: [`${{ needs.validate.outputs.branch || 'N/A' }}`](${{ github.server_url }}/${{ github.repository }}/tree/${{ needs.validate.outputs.branch }})
            **Run**: [View workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
