name: Mark Release Deployed

on:
  repository_dispatch:
    types: [deployment_build_deployed_command]

jobs:
  mark:
    runs-on: ubuntu-latest
    steps:
      - name: Remove production label from all other issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          ISSUE_NUMBER="${{ github.event.client_payload.github.payload.issue.number }}"
          REPO="${{ github.repository }}"

          echo "Removing 'production' label from all other issues (open/closed)"
          OTHER_ISSUES=$(gh issue list \
            --repo "$REPO" \
            --label "production" \
            --state all \
            --limit 100 \
            --json number \
            --jq '.[].number' | grep -vx "$ISSUE_NUMBER" || true)

          for i in $OTHER_ISSUES; do
            echo "Removing production label from issue #$i"
            gh issue edit "$i" --repo "$REPO" --remove-label "production" || true
          done

          echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_ENV"

      - name: Add release_deployed and production labels to current issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit "$ISSUE_NUMBER" \
            --repo "${{ github.repository }}" \
            --add-label "release_deployed" \
            --add-label "production"

      - name: Post confirmation comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          body: |
            ✅ **Release marked as deployed to production**

            🏷️ Labels applied: `release_deployed`, `production`

            [View this workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
