name: Build and Deploy from Tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print deployment parameters
        run: |
          echo "🔧 Deploying with parameters:"
          echo "  - tag: ${{ inputs.tag }}"
          echo "  - environment: ${{ inputs.environment }}"
          echo "  - branch: ${{ inputs.branch }}"

      - name: Checkout Loop Tags
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0

      - name: Git setup
        working-directory: src
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Checkout source repo at tag
        uses: actions/checkout@v4
        with:
          repository: IQSS/ondemand-loop
          ref: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src

      - name: Build release
        working-directory: src
        run: make release_build

      - name: Checkout Loop Environment Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: target

      - name: Copy Loop new version
        run: |
          rsync -a --delete --exclude='.git' src/application/ target/

      - name: List contents of target
        run: ls -la target/

      - name: Commit production release
        working-directory: target
        run: |
          git add .
          git commit -m "OnDemand Loop deployment for version ${{ inputs.tag }}"
          git push
