name: Deploy Dataverse Landing

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - production
          - production_main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: dv-landing-${{ github.event.inputs.environment }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source
          fetch-depth: 0  # Needed for tag checkout

      - name: Create site folder
        run: mkdir -p site/qa

      - name: Build for production
        if: ${{ github.event.inputs.environment == 'production' }}
        working-directory: source
        run: |
          git checkout production_deployed
          cp -R dv_external_tools ../site/
          
      - name: Build for production from main
        if: ${{ github.event.inputs.environment == 'production_main' }}
        working-directory: source
        run: |
          git checkout origin/main
          cp -R dv_external_tools ../site/

      - name: Build for QA
        if: ${{ github.event.inputs.environment == 'qa' }}
        working-directory: source
        run: |
          # Step 1: production build into root
          git checkout production_deployed
          cp -R dv_external_tools ../site/

          # Step 2: head build into /qa
          git checkout origin/main
          cp -R dv_external_tools ../site/qa/

      - name: List all files under site/
        run: |
          echo "📂 All files under site/:"
          find site -type f

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
