name: Create Release

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string
      release_type:
        required: true
        type: string
    outputs:
      version:
        description: "The version number created"
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout FASRC Config
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src

      - name: Git setup
        working-directory: src
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Create release temp branch
        working-directory: src
        run: |
          git fetch origin
          git checkout -b release-temp ${{ inputs.commit_hash }}

      - name: Create release notes
        working-directory: src
        run: make release_notes

      - name: Bump version using Docker via Make
        working-directory: src
        run: make version VERSION_TYPE=${{ inputs.release_type }}

      - name: Commit bumped version to temp branch
        working-directory: src
        run: |
          git add VERSION
          git commit -m "Create release version"
          git push -f origin release-temp

      - name: Read current version
        id: version
        working-directory: src
        run: |
          source ../.github/scripts/utils.sh

          version=v$(cat VERSION)
          set_output "version" "$version"

      - name: Create and push tag
        working-directory: src
        run: |
          git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push origin "${{ steps.version.outputs.version }}"

      - name: Cherry-pick VERSION commit to main
        working-directory: src
        run: |
          VERSION_COMMIT=$(git rev-parse HEAD)
          git checkout main
          git pull origin main
          git cherry-pick "$VERSION_COMMIT"
          git push origin main

      - name: Delete release temp branch
        working-directory: src
        run: |
          git push origin --delete release-temp || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          body_path: src/release_notes.md
