name: FASRC Command Listener

on:
  issue_comment:
    types: [created]

jobs:
  slash-command:
    if: contains(github.event.comment.body, '/deployment_build')
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is authorized
        uses: actions/github-script@v7
        with:
          script: |
            const allowed = ['abujeda','whorka','doprdele'];
            const user = context.payload.comment.user.login;
            if (!allowed.includes(user)) {
              core.setFailed(`❌ User ${user} is not allowed to run this command.`);
            }

      - uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: issue
          event-type-suffix: _command
          commands: |
            deployment_build_candidate
            deployment_build_release
            deployment_build_deployed
          permission: none
